name: Black / Automaticly Triggered Python Autoformatter

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip
        python -m pip install black
        python -m black --config black.toml azureiai tests

        git config --global user.email "auto-black@noreply.github.com"
        git config --global user.name "Auto Black"

        git add azureiai tests

        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto Black Formatting Action" --no-edit --allow-empty
          git push --force-with-lease
        fi
