name: wemake-python-styleguide

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.15.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: azure
          reporter: github-pr-review
