
name: PyTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Set Configurations
        run: |
          echo "tenant_id: \"${{ secrets.TENANT_ID }}\"" >> config.yml
          echo "azure_preview_subscription: \"${{ secrets.SUBSCRIPTION_ID }}\"" >> config.yml
          echo "aad_id: \"${{ secrets.AAD_ID }}\"" >> config.yml
          echo "aad_secret: \"${{ secrets.AAD_SECRET }}\"" >> config.yml
          echo "access_id: \"${{ secrets.ACCESS_ID }}\"" >> config.yml
          echo "publisherId: \"${{ secrets.PUBLISHER_ID }}\"" >> config.yml
          
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
          pip install -r requirements.txt 
          pip install pytest-cov coverage pytest-github-actions-annotate-failures
          pytest -m "not integration and not gpu" -c tox.ini tests

          coverage erase
          python3 -m pytest \
             -c "tox.ini" \
             -m "not integration and not gpu" \
             --cov-append \
             --cov-config ".coveragerc" \
             --cov azureiai \
             "tests"

          coverage report -m --skip-covered >> pytest-coverage.txt
          cat pytest-coverage.txt
      # Show unit test code coverage in a pull request comment.
      - name: Show coverage comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: MishaKav/pytest-coverage-comment@v1.1.24
        continue-on-error: true
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest-results.xml
        
#       - name: Tox Env Unit
#         uses: paolorechia/pox@v1.0.1
#         with:
#           tox_env: py37-unit
#       - name: Tox Env Integration
#         uses: paolorechia/pox@v1.0.1
#         with:
#           tox_env: py37-integration        
