name: "Semantic PR Check"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  set-labels:
    runs-on: ubuntu-latest
    steps:
      - name: pr-auto-label
        uses: actions-cool/pr-auto-label@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enum: 'feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert'
          format: '${type}:'
          extra: 'feat/feature, docs/doc, test/tests'
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
